### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: authClient.request is not a function

### ISSUE THREAD

**Issue by atifabdussamad** [gsuitedevs/node-samples#22]
## Actual Behavior
(node:4104) UnhandledPromiseRejectionWarning: TypeError: authClient.request is not a function
    at Object.createAPIRequest (C:\Users\atifs\WebstormProjects\eventScheduler\node_modules\googleapis\build\src\lib\apirequest.js:193:20)
    at Object.list (C:\Users\atifs\WebstormProjects\eventScheduler\node_modules\googleapis\build\src\apis\calendar\v3.js:684:33)
    at listEvents (C:\Users\atifs\WebstormProjects\eventScheduler\index.js:72:21)
    at oAuth2Client.getToken (C:\Users\atifs\WebstormProjects\eventScheduler\index.js:54:29)
    at C:\Users\atifs\WebstormProjects\eventScheduler\node_modules\google-auth-library\build\src\auth\oauth2client.js:158:46
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Node version (`node -v`)
  - OS (Mac/Linux/Windows)

**Comment by erickoledadevrel** [comment]
See #18
