### ISSUE TITLE
After following quick start steps: Unexpected end of JSON input     at JSON.parse (<anonymous>)

### ISSUE THREAD

**Issue by Jtech42** [gsuitedevs/node-samples#25]
## Expected Behavior
a demo

## Actual Behavior
Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at fs.readFile (/Users/JJ/Desktop/AutoTests/index.js:30:38)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)

## Steps to Reproduce the Problem

  1. follow all steps at: https://developers.google.com/gmail/api/quickstart/nodejs

**Comment by grant** [comment]
@Jtech42 This means that the `credentials.json` is corrupt.
- Can you check if the file is correct?
- Can you delete the file and try running the sample again?

**Comment by grant** [comment]
The `JSON.parse` error should be a problem with the JSON file.
Closing due to inactivity. Comment here if you want me to re-open this issue.
