### ISSUE TITLE
Firebase Callable Function with googleapis and JWT: google.options({ auth: jwt });

### ISSUE THREAD

**Issue by alexpilugin** [gsuitedevs/node-samples#31]
[My question](https://stackoverflow.com/questions/52311086/firebase-callable-function-with-jwt-authentication-and-google-sheets-v4-api)

## Expected Behavior
sheets.spreadsheets.values.get(request, (err, response) => {
var rows = response.values;
//Expected: rows.length > 0

## Actual Behavior

TypeError: Cannot read property 'length' of undefined
    at sheets.spreadsheets.values.get.err (/user_code/index.js:71:17)
    at createAPIRequestAsync.then.r (/user_code/node_modules/googleapis/node_modules/googleapis-common/build/src/apirequest.js:49:53)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

## Steps to Reproduce the Problem

  1. Generate Admin Service Account Key .json file
  2. Make a clone (save on My Drive) of the Example Spreadsheet:
https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit
  3. Obtain "client_email" from  Admin Service Account Key .json file and share a new spreadsheet with this specific user.
  4. Use code from index.js: [Firebase Callable Function with JWT Authentication and Google Sheets v4 API](https://stackoverflow.com/questions/52311086/firebase-callable-function-with-jwt-authentication-and-google-sheets-v4-api)

## Specifications

  - Node version (`node -v`)  v8.9.4
  - OS (Mac/Linux/Windows) MacOS High Sierra 10.13.4 (17E199)

**Comment by alexpilugin** [comment]
The issue was next: googleapis after the version of v26.0.1 returns: <br>
`var rows = response.data.values; `
not: `var rows = response.values;` //as before

Issue closed.
