### ISSUE TITLE
Not able to create new spreadsheets from Node.JS using Google Sheets API v4 

### ISSUE THREAD

**Issue by rahuliet** [gsuitedevs/node-samples#40]
## Expected Behavior
Spreadsheet should get created 

## Actual Behavior
No spreadsheet is getting created

## Steps to Reproduce the Problem

**Execute the below code and refer to create new spreadsheet function** 

```
const fs = require('fs');
const readline = require('readline');
const {google} = require('googleapis');

// If modifying these scopes, delete token.json.
const SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly'];
// The file token.json stores the user's access and refresh tokens, and is
// created automatically when the authorization flow completes for the first
// time.
const TOKEN_PATH = 'token.json';

// Load client secrets from a local file.
fs.readFile('credentials.json', (err, content) => {
  if (err) return console.log('Error loading client secret file:', err);
  // Authorize a client with credentials, then call the Google Sheets API.
  authorize(JSON.parse(content), listMajors);
});

/**
 * Create an OAuth2 client with the given credentials, and then execute the
 * given callback function.
 * @param {Object} credentials The authorization client credentials.
 * @param {function} callback The callback to call with the authorized client.
 */
function authorize(credentials, callback) {
  const {client_secret, client_id, redirect_uris} = credentials.installed;
  const oAuth2Client = new google.auth.OAuth2(
      client_id, client_secret, redirect_uris[0]);

  // Check if we have previously stored a token.
  fs.readFile(TOKEN_PATH, (err, token) => {
    if (err) return getNewToken(oAuth2Client, callback);
    oAuth2Client.setCredentials(JSON.parse(token));
    callback(oAuth2Client);
  });
}

/**
 * Get and store new token after prompting for user authorization, and then
 * execute the given callback with the authorized OAuth2 client.
 * @param {google.auth.OAuth2} oAuth2Client The OAuth2 client to get token for.
 * @param {getEventsCallback} callback The callback for the authorized client.
 */
function getNewToken(oAuth2Client, callback) {
  const authUrl = oAuth2Client.generateAuthUrl({
    access_type: 'offline',
    scope: SCOPES,
  });
  console.log('Authorize this app by visiting this url:', authUrl);
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  rl.question('Enter the code from that page here: ', (code) => {
    rl.close();
    oAuth2Client.getToken(code, (err, token) => {
      if (err) return console.error('Error while trying to retrieve access token', err);
      oAuth2Client.setCredentials(token);
      // Store the token to disk for later program executions
      fs.writeFile(TOKEN_PATH, JSON.stringify(token), (err) => {
        if (err) console.error(err);
        console.log('Token stored to', TOKEN_PATH);
      });
      callback(oAuth2Client);
    });
  });
}

/**
 * Prints the names and majors of students in a sample spreadsheet:
 * @see https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit
 * @param {google.auth.OAuth2} auth The authenticated Google OAuth client.
 */
function listMajors(auth) {
  const sheets = google.sheets({version: 'v4', auth});
  sheets.spreadsheets.values.get({
    spreadsheetId: '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    range: 'Class Data!A2:E',
  }, (err, res) => {
    if (err) return console.log('The API returned an error: ' + err);
    const rows = res.data.values;
    if (rows.length) {
      console.log('Name, Major:');
      // Print columns A and E, which correspond to indices 0 and 4.
      rows.map((row) => {
        console.log(`${row[0]}, ${row[4]}`);
      });
    } else {
      console.log('No data found.');
    }
  });
}


function createNewSpreadSheet(auth) {
	  const sheets = google.sheets({version: 'v4', auth});
  const resource = {
  properties: {
    title:'SampleSheet'
  },
};
sheets.sheetsService.spreadsheets.create({
  resource,
  fields: 'spreadsheetId',
}, (err, spreadsheet) =>{
  if (err) {
    // Handle error.
    console.log(err);
  } else {
    console.log(`Spreadsheet ID: ${spreadsheet.spreadsheetId}`);
  }
});
}
createNewSpreadSheet();
```
## Specifications

  - Node version (`node -v`)
  - OS (Mac/Linux/Windows)

**Comment by grant** [comment]
What do you see instead? Please fill out the issue details.

**Comment by grant** [comment]
The code above isn’t a sample we’ve created. The issue you’ve described isn’t an issue with an existing sample.

I think the issue you’re having is around the readonly scope. If you fix the scope issue, you may not have the problem.

**Comment by rahuliet** [comment]
****

even if scope is fixed from 
**

> readonly to https://www.googleapis.com/auth/spreadsheets

**

I am getting below error

`sheets.sheetsService.spreadsheets.create({
                     ^

TypeError: Cannot read property 'spreadsheets' of undefined
    at createNewSpreadSheet (c:\work\TalentScore_GS\app.js:102:22)
    at Object.<anonymous> (c:\work\TalentScore_GS\app.js:114:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

**Comment by rahuliet** [comment]
purpose of code is to create a new spreadsheet from scratch using Node.js on google drive

**Comment by erickoledadevrel** [comment]
As @grant alluded to, this issue tracker is for problems with our sample code. Once you've modified the sample code if you have problems you should use the standard support channels:

https://developers.google.com/sheets/api/support

It this case it looks like you should be using `sheets.spreadsheets.create`, since `sheetsService` isn't defined anywhere.
