### ISSUE TITLE
quickstart generated credentials.json doesn't match codebase

### ISSUE THREAD

**Issue by rbaindourov** [gsuitedevs/node-samples#81]
## Expected Behavior
Consumes credentials.json correctly

I am actually looking for an example to send an email via my gmail account.
First from a web form to my gmail account. 
Later CRM integration.

## Actual Behavior
is looking for .installed but I have .web
is looking for redirect_uri's when none exist
```
robert@pop-os:~/projects/googleapi-node-samples/gmail/quickstart$ npm run start

> gmail-nodejs-quickstart@1.0.0 start /home/robert/projects/googleapi-node-samples/gmail/quickstart
> node .

/home/robert/projects/googleapi-node-samples/gmail/quickstart/index.js:27
  const {client_secret, client_id, redirect_uris} = credentials.installed;
         ^

TypeError: Cannot destructure property `client_secret` of 'undefined' or 'null'.
    at authorize (/home/robert/projects/googleapi-node-samples/gmail/quickstart/index.js:27:65)
    at fs.readFile (/home/robert/projects/googleapi-node-samples/gmail/quickstart/index.js:17:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gmail-nodejs-quickstart@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gmail-nodejs-quickstart@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/robert/.npm/_logs/2019-07-27T22_37_26_016Z-debug.log
```

changed to .web but then get this following error. 

```
> gmail-nodejs-quickstart@1.0.0 start /home/robert/projects/googleapi-node-samples/gmail/quickstart
> node .

/home/robert/projects/googleapi-node-samples/gmail/quickstart/index.js:29
      client_id, client_secret, redirect_uris[0]);
                                             ^

TypeError: Cannot read property '0' of undefined
    at authorize (/home/robert/projects/googleapi-node-samples/gmail/quickstart/index.js:29:46)
    at fs.readFile (/home/robert/projects/googleapi-node-samples/gmail/quickstart/index.js:17:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gmail-nodejs-quickstart@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gmail-nodejs-quickstart@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/robert/.npm/_logs/2019-07-27T22_35_12_847Z-debug.log
```

## Steps to Reproduce the Problem

  1. Follow quickstart tutorial
  2. Enable Gmail API
  3. Download credentials.json
  4. Clone node-samples
  5. place credentials.json into gmail/quickstart
  6. npm i
  7. npm run start

## Specifications

node -v
v10.16.0

Ubuntu Cosmic.

**Comment by rbaindourov** [comment]
Never mind, have to generate the credentials.json from NodeJS quickstart page.

**Comment by marcusmoore** [comment]
I just ran into this as well. For future reference: click the big blue `Enable The Drive API` button
![image](https://user-images.githubusercontent.com/1141514/62350393-76673180-b4b7-11e9-8bac-67cd087bd45b.png)

Then you'll be able to download the client configuration.
![image](https://user-images.githubusercontent.com/1141514/62350442-9565c380-b4b7-11e9-93be-4428351d7be1.png)

(I tried to use the configuration I got from the console)
