### ISSUE TITLE
TypeError: Cannot destructure property 'client_secret' of 'credentials.installed ' as it is undefined.

### ISSUE THREAD

**Issue by salmansrabon** [gsuitedevs/node-samples#98]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Node version (`node -v`)
  - OS (Mac/Linux/Windows)

**Comment by billythemusical** [comment]
Working in sheets > examples > quickstart, when making the `node .` command:

**Expected Behavior**

For the app to launch.

**Actual Behavior**

Error message:
```
$ node .
/Users/williambennett/Documents/GitHub/node-samples/sheets/quickstart/index.js:43
  const {client_secret, client_id, redirect_uris} = credentials.installed;
         ^

TypeError: Cannot destructure property `client_secret` of 'undefined' or 'null'.
    at authorize (/Users/williambennett/Documents/GitHub/node-samples/sheets/quickstart/index.js:43:65)
    at fs.readFile (/Users/williambennett/Documents/GitHub/node-samples/sheets/quickstart/index.js:33:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Steps to Reproduce the Problem**

Clone the repo, download `credentials.json` to the quickstart directory, run `npm install` then `npm install googleapis@39 --save`.  Launch the app by running `node .`

**Specifications**

Node version (node -v) - v10.21.0
OS (Mac/Linux/Windows) - Mac OSX Mojave 10.14.3

**Attached error message screenshot:**
![Screen Shot 2020-07-11 at 4 56 02 PM](https://user-images.githubusercontent.com/40703526/87233853-37b14b00-c399-11ea-8d39-4508281ec39a.png)

**Comment by billythemusical** [comment]
Same as Issue #92

**Comment by kingmaker9841** [comment]
Same as issue #92

**Comment by sidharathjain2** [comment]
Same as issue #92

**Comment by mr-winson** [comment]
change credentials.installed to credentials.web

**Comment by working-name** [comment]
> change credentials.installed to credentials.web

More context please, I've grepped the project folder, and all clasp json every where, no hits. It also seems you need to manually generate .clasprc.json ?! Terrible documentation on this process.

**Comment by alechash** [comment]
Oh man, I haven't used this since my last comment, try mentioning a contributor or something

**Comment by working-name** [comment]
> Oh man, I haven't used this since my last comment, try mentioning a contributor or something, @working-name

Thank you much for replying! That's quite alright, I ended up giving up on clasp run, just doing a POST from AS to log things more easily.

**Comment by dcsan** [comment]
is there any way to get this to work with a service account for server to server, so we don't need a redirect URL?

**Comment by alechash** [comment]
I'd open another issue, might get a contributor to help out maybe

**Comment by dcsan** [comment]
in case anyone needs this for sheets I gave up with the oauth examples in this repo and just used something like this 

```ts
const fs = require('fs')

const { google } = require('googleapis');
const docs = require('@googleapis/docs')

// replace these two
const credsPath = './your-service-account.json';
const sheetId = 'XXXX-your-sheet-id'

async function getAuth() {

    const auth = new docs.auth.GoogleAuth({
        keyFilename: credsPath,
        // Scopes can be specified either as an array or as a single, space-delimited string.
        scopes: [
            'https://www.googleapis.com/auth/spreadsheets.readonly',
            'https://www.googleapis.com/auth/spreadsheets'
        ]
    });
    const authClient = await auth.getClient();
    return auth;
}


async function fetchClues(auth: any): Promise<any[]> {
    const sheets = google.sheets({ version: 'v4', auth });
    const result = await sheets.spreadsheets.values.get({
        spreadsheetId: sheetId,
        range: 'clues!A1:E100',
    })
    return result.data.values;
}

async function main () {
    await DbConn.connect()
    const auth = await getAuth();
    const rows: any[] = await fetchClues(auth);
    // const msg = `reset ${BoxData.length}`
    console.log('reset', boxes)
    console.log('boxes.length', boxes.length)
    DbConn.close() // or the process won't close
}

process.on('unhandledexception', (err) => {
    console.log('unhandledexception', err);
});



main()
```
